"""HPC Environment Modules profile generator.

Many HPC clusters use Environment Modules (or Lmod) instead of containers.
nf-core pipelines support a `modules.config` that maps process labels to
`module load` directives.  This module generates that config from helixsh's
tool database so users can run nf-core pipelines on container-less clusters.

Output format: Nextflow `modules.config` with `withName` selectors and
`module` directives — ready to be passed via `-c modules.config` or merged
into the user's `nextflow.config`.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path

# Default module names per tool on common HPC clusters.
# Format: tool_key -> {module_name, version_hint}
# Users can override the version via --module-version flags.
_MODULE_DB: dict[str, dict[str, str]] = {
    # Aligners
    "star":        {"module": "STAR",         "version": "2.7.11b"},
    "hisat2":      {"module": "HISAT2",       "version": "2.2.1"},
    "bwa":         {"module": "BWA",          "version": "0.7.17"},
    "bwa-mem2":    {"module": "BWA-MEM2",     "version": "2.2.1"},
    "minimap2":    {"module": "Minimap2",     "version": "2.28"},
    "bowtie2":     {"module": "Bowtie2",      "version": "2.5.4"},
    "salmon":      {"module": "Salmon",       "version": "1.10.3"},
    "kallisto":    {"module": "kallisto",     "version": "0.51.1"},
    "bismark":     {"module": "Bismark",      "version": "0.24.2"},
    # Variant calling
    "gatk4":       {"module": "GATK",         "version": "4.6.0.0"},
    "deepvariant": {"module": "DeepVariant",  "version": "1.6.1"},
    "bcftools":    {"module": "BCFtools",     "version": "1.21"},
    "strelka2":    {"module": "Strelka",      "version": "2.9.10"},
    # QC / trimming
    "fastqc":      {"module": "FastQC",       "version": "0.12.1"},
    "fastp":       {"module": "fastp",        "version": "0.23.4"},
    "trimgalore":  {"module": "TrimGalore",   "version": "0.6.10"},
    "multiqc":     {"module": "MultiQC",      "version": "1.26"},
    # Post-processing
    "samtools":    {"module": "SAMtools",     "version": "1.21"},
    "picard":      {"module": "picard",       "version": "3.2.0"},
    "deeptools":   {"module": "deepTools",    "version": "3.5.5"},
    "bedtools":    {"module": "BEDTools",     "version": "2.31.1"},
    "subread":     {"module": "Subread",      "version": "2.0.6"},
    # Single-cell
    "cellranger":  {"module": "CellRanger",   "version": "8.0.1"},
    # Python / R
    "python":      {"module": "Python",       "version": "3.12.7"},
    "r":           {"module": "R",            "version": "4.4.2"},
}


@dataclass
class ModuleEntry:
    process_selector: str
    module_name: str
    module_version: str
    full_module: str   # e.g. "STAR/2.7.11b"


@dataclass
class EnvModulesConfig:
    entries: list[ModuleEntry] = field(default_factory=list)
    warnings: list[str] = field(default_factory=list)

    def to_nextflow_config(self) -> str:
        """Render a Nextflow modules.config string."""
        lines = [
            "// Auto-generated by helixsh envmodules-wrap",
            "// Pass to Nextflow with: -c modules.config",
            "process {",
        ]
        for entry in self.entries:
            lines.append(f"    withName: '{entry.process_selector}' {{")
            lines.append(f"        module = '{entry.full_module}'")
            lines.append("    }")
        lines.append("}")
        return "\n".join(lines) + "\n"


def list_known_modules() -> list[dict[str, str]]:
    return [
        {"tool": tool, "module": info["module"], "default_version": info["version"]}
        for tool, info in sorted(_MODULE_DB.items())
    ]


def generate_modules_config(
    tools: list[str],
    version_overrides: dict[str, str] | None = None,
    process_selector_prefix: str = "",
) -> EnvModulesConfig:
    """Generate a Nextflow modules.config for the given tool list."""
    overrides = version_overrides or {}
    config = EnvModulesConfig()

    for tool in tools:
        tool_norm = tool.strip().lower()
        if tool_norm not in _MODULE_DB:
            config.warnings.append(f"Unknown tool '{tool}' — skipped. Use --module-name to specify manually.")
            continue
        info = _MODULE_DB[tool_norm]
        version = overrides.get(tool_norm, info["version"])
        module_name = info["module"]
        full_module = f"{module_name}/{version}"

        # Default process selector: uppercase tool name, optionally prefixed
        selector = f"{process_selector_prefix}{tool_norm.upper().replace('-', '_')}"

        config.entries.append(ModuleEntry(
            process_selector=selector,
            module_name=module_name,
            module_version=version,
            full_module=full_module,
        ))

    return config


def write_modules_config(config: EnvModulesConfig, out_path: str) -> None:
    p = Path(out_path)
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(config.to_nextflow_config(), encoding="utf-8")
